### ISSUE TITLE
NoSuchMethodError: Class 'String' has no instance method '>'.

### ISSUE THREAD

**Issue by fenchai23** [deependra227/multi-sort#2]
`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: Class 'String' has no instance method '>'.`

any way to fix this error? 

I am trying to fix a `List<CartItem>` I need to sort by `group` then by `code`.

`_cartItems.multisort([false, false], ['group', 'code']);` not sure if this is the right way to sort.

```
class CartItem {
  String qty;
  final String code;
  final String desc;
  final String invt;
  final String codealt;
  final String descalt;
  final String group;
  final String price;
  final String disc1;
  String globalPrice;
  String total;
  bool isSelected;

  CartItem(
      this.qty,
      this.code,
      this.desc,
      this.invt,
      this.codealt,
      this.descalt,
      this.group,
      this.price,
      this.disc1,
      this.globalPrice,
      this.total,
      {this.isSelected = false});

  CartItem.fromJson(Map<String, dynamic> json)
      : qty = json['qty'],
        code = json['code'],
        desc = json['desc'],
        invt = json['invt'],
        codealt = json['codealt'],
        descalt = json['descalt'],
        group = json['group'],
        price = json['price'],
        disc1 = json['disc1'],
        globalPrice = json['globalPrice'],
        total = json['total'],
        isSelected = false;

  Map<String, dynamic> toJson() {
    return {
      "qty": this.qty,
      "code": this.code,
      "desc": this.desc,
      "invt": this.invt,
      "codealt": this.codealt,
      "descalt": this.descalt,
      "group": this.group,
      "price": this.price,
      "disc1": this.disc1,
      "globalPrice": this.globalPrice,
      "total": this.total,
    };
  }

  ///get function to get the properties of Item
  dynamic get(String propertyName) {
    var _mapRep = toJson();
    if (_mapRep.containsKey(propertyName)) {
      return _mapRep[propertyName];
    }
    throw ArgumentError('propery not found');
  }
}
```

**Comment by deependra227** [comment]
Try to edit the multi_sort.dart file in lib
replace  ```else if (a.get(preferrence[i]) > b.get(preferrence[i]))``` with
     ``` else if (a.get(preferrence[i]).compareTo(b.get(preferrence[i])) > 0)``` 
And let me know if it works or not. I'll fix this when I get free.

**Comment by thomasschwarzott** [comment]
@deependra227 I faced the same problem as I wanted to compare strings. Funnily I fixed it for myself first and then looked for this issue here. I can confirm that "our" solution works :) 

Oh and by the way, as far as I can see, `preferrence` can be typed as a `List<String>`.

**Comment by fenchai23** [comment]
It's awesome you can confirm it works, because I feel bad for not being able to test, I went for another native solution instead of package dependent and don't have the time to setup/test properly.

Feel free to close this if there is a need.

**Comment by deependra227** [comment]
@thomasschwarzott Thank you for the confirmation.
