### ISSUE TITLE
add to be able to sort by date

### ISSUE THREAD

**Issue by xmartinez22** [deependra227/multi-sort#5]
Class 'String' has no instance method '>'.
Receiver: "2021-02-16T00:00:00.000"
Tried calling: >("2021-02-18T00:00:00.000")

'useDate': useDate.toIso8601String(), or 'useDate' : useDate does not work either

**Comment by deependra227** [comment]
Read #2 . And let me if it worked.

**Comment by xmartinez22** [comment]
Yes! thank you!
